/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ntt.travelhub.viaje.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Viaje service. Represents a row in the &quot;Viaje_Viaje&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntt.travelhub.viaje.model.impl.ViajeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntt.travelhub.viaje.model.impl.ViajeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Viaje
 * @generated
 */
@ProviderType
public interface ViajeModel
	extends BaseModel<Viaje>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a viaje model instance should use the {@link Viaje} interface instead.
	 */

	/**
	 * Returns the primary key of this viaje.
	 *
	 * @return the primary key of this viaje
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this viaje.
	 *
	 * @param primaryKey the primary key of this viaje
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this viaje.
	 *
	 * @return the uuid of this viaje
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this viaje.
	 *
	 * @param uuid the uuid of this viaje
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the viaje ID of this viaje.
	 *
	 * @return the viaje ID of this viaje
	 */
	public long getViajeId();

	/**
	 * Sets the viaje ID of this viaje.
	 *
	 * @param viajeId the viaje ID of this viaje
	 */
	public void setViajeId(long viajeId);

	/**
	 * Returns the group ID of this viaje.
	 *
	 * @return the group ID of this viaje
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this viaje.
	 *
	 * @param groupId the group ID of this viaje
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this viaje.
	 *
	 * @return the company ID of this viaje
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this viaje.
	 *
	 * @param companyId the company ID of this viaje
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this viaje.
	 *
	 * @return the user ID of this viaje
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this viaje.
	 *
	 * @param userId the user ID of this viaje
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this viaje.
	 *
	 * @return the user uuid of this viaje
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this viaje.
	 *
	 * @param userUuid the user uuid of this viaje
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this viaje.
	 *
	 * @return the user name of this viaje
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this viaje.
	 *
	 * @param userName the user name of this viaje
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this viaje.
	 *
	 * @return the create date of this viaje
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this viaje.
	 *
	 * @param createDate the create date of this viaje
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this viaje.
	 *
	 * @return the modified date of this viaje
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this viaje.
	 *
	 * @param modifiedDate the modified date of this viaje
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the origen of this viaje.
	 *
	 * @return the origen of this viaje
	 */
	@AutoEscape
	public String getOrigen();

	/**
	 * Sets the origen of this viaje.
	 *
	 * @param origen the origen of this viaje
	 */
	public void setOrigen(String origen);

	/**
	 * Returns the destino of this viaje.
	 *
	 * @return the destino of this viaje
	 */
	@AutoEscape
	public String getDestino();

	/**
	 * Sets the destino of this viaje.
	 *
	 * @param destino the destino of this viaje
	 */
	public void setDestino(String destino);

	/**
	 * Returns the fecha salida of this viaje.
	 *
	 * @return the fecha salida of this viaje
	 */
	public Date getFechaSalida();

	/**
	 * Sets the fecha salida of this viaje.
	 *
	 * @param fechaSalida the fecha salida of this viaje
	 */
	public void setFechaSalida(Date fechaSalida);

	/**
	 * Returns the fecha llegada of this viaje.
	 *
	 * @return the fecha llegada of this viaje
	 */
	public Date getFechaLlegada();

	/**
	 * Sets the fecha llegada of this viaje.
	 *
	 * @param fechaLlegada the fecha llegada of this viaje
	 */
	public void setFechaLlegada(Date fechaLlegada);

	/**
	 * Returns the empresa of this viaje.
	 *
	 * @return the empresa of this viaje
	 */
	@AutoEscape
	public String getEmpresa();

	/**
	 * Sets the empresa of this viaje.
	 *
	 * @param empresa the empresa of this viaje
	 */
	public void setEmpresa(String empresa);

	/**
	 * Returns the precio of this viaje.
	 *
	 * @return the precio of this viaje
	 */
	public double getPrecio();

	/**
	 * Sets the precio of this viaje.
	 *
	 * @param precio the precio of this viaje
	 */
	public void setPrecio(double precio);

	/**
	 * Returns the asientos disponibles of this viaje.
	 *
	 * @return the asientos disponibles of this viaje
	 */
	public int getAsientosDisponibles();

	/**
	 * Sets the asientos disponibles of this viaje.
	 *
	 * @param asientosDisponibles the asientos disponibles of this viaje
	 */
	public void setAsientosDisponibles(int asientosDisponibles);

	@Override
	public Viaje cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}