/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ntt.travelhub.viaje.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.ntt.travelhub.viaje.model.Viaje;
import com.ntt.travelhub.viaje.model.ViajeModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Viaje service. Represents a row in the &quot;Viaje_Viaje&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ViajeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViajeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ViajeImpl
 * @generated
 */
@JSON(strict = true)
public class ViajeModelImpl extends BaseModelImpl<Viaje> implements ViajeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a viaje model instance should use the <code>Viaje</code> interface instead.
	 */
	public static final String TABLE_NAME = "Viaje_Viaje";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"viajeId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"origen", Types.VARCHAR}, {"destino", Types.VARCHAR},
		{"fechaSalida", Types.TIMESTAMP}, {"fechaLlegada", Types.TIMESTAMP},
		{"empresa", Types.VARCHAR}, {"precio", Types.DOUBLE},
		{"asientosDisponibles", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("viajeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("origen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("destino", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fechaSalida", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fechaLlegada", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("empresa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("precio", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("asientosDisponibles", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Viaje_Viaje (uuid_ VARCHAR(75) null,viajeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,origen VARCHAR(75) null,destino VARCHAR(75) null,fechaSalida DATE null,fechaLlegada DATE null,empresa VARCHAR(75) null,precio DOUBLE,asientosDisponibles INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table Viaje_Viaje";

	public static final String ORDER_BY_JPQL =
		" ORDER BY viaje.fechaSalida ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Viaje_Viaje.fechaSalida ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESTINO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPRESA_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ORIGEN_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FECHASALIDA_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ViajeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _viajeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setViajeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _viajeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Viaje.class;
	}

	@Override
	public String getModelClassName() {
		return Viaje.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Viaje, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Viaje, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Viaje, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Viaje)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Viaje, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Viaje, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Viaje)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Viaje, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Viaje, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Viaje, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Viaje, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Viaje, Object>>();

			attributeGetterFunctions.put("uuid", Viaje::getUuid);
			attributeGetterFunctions.put("viajeId", Viaje::getViajeId);
			attributeGetterFunctions.put("groupId", Viaje::getGroupId);
			attributeGetterFunctions.put("companyId", Viaje::getCompanyId);
			attributeGetterFunctions.put("userId", Viaje::getUserId);
			attributeGetterFunctions.put("userName", Viaje::getUserName);
			attributeGetterFunctions.put("createDate", Viaje::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Viaje::getModifiedDate);
			attributeGetterFunctions.put("origen", Viaje::getOrigen);
			attributeGetterFunctions.put("destino", Viaje::getDestino);
			attributeGetterFunctions.put("fechaSalida", Viaje::getFechaSalida);
			attributeGetterFunctions.put(
				"fechaLlegada", Viaje::getFechaLlegada);
			attributeGetterFunctions.put("empresa", Viaje::getEmpresa);
			attributeGetterFunctions.put("precio", Viaje::getPrecio);
			attributeGetterFunctions.put(
				"asientosDisponibles", Viaje::getAsientosDisponibles);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Viaje, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Viaje, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Viaje, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Viaje, String>)Viaje::setUuid);
			attributeSetterBiConsumers.put(
				"viajeId", (BiConsumer<Viaje, Long>)Viaje::setViajeId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Viaje, Long>)Viaje::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Viaje, Long>)Viaje::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Viaje, Long>)Viaje::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Viaje, String>)Viaje::setUserName);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Viaje, Date>)Viaje::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Viaje, Date>)Viaje::setModifiedDate);
			attributeSetterBiConsumers.put(
				"origen", (BiConsumer<Viaje, String>)Viaje::setOrigen);
			attributeSetterBiConsumers.put(
				"destino", (BiConsumer<Viaje, String>)Viaje::setDestino);
			attributeSetterBiConsumers.put(
				"fechaSalida", (BiConsumer<Viaje, Date>)Viaje::setFechaSalida);
			attributeSetterBiConsumers.put(
				"fechaLlegada",
				(BiConsumer<Viaje, Date>)Viaje::setFechaLlegada);
			attributeSetterBiConsumers.put(
				"empresa", (BiConsumer<Viaje, String>)Viaje::setEmpresa);
			attributeSetterBiConsumers.put(
				"precio", (BiConsumer<Viaje, Double>)Viaje::setPrecio);
			attributeSetterBiConsumers.put(
				"asientosDisponibles",
				(BiConsumer<Viaje, Integer>)Viaje::setAsientosDisponibles);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getViajeId() {
		return _viajeId;
	}

	@Override
	public void setViajeId(long viajeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_viajeId = viajeId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getOrigen() {
		if (_origen == null) {
			return "";
		}
		else {
			return _origen;
		}
	}

	@Override
	public void setOrigen(String origen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_origen = origen;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalOrigen() {
		return getColumnOriginalValue("origen");
	}

	@JSON
	@Override
	public String getDestino() {
		if (_destino == null) {
			return "";
		}
		else {
			return _destino;
		}
	}

	@Override
	public void setDestino(String destino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_destino = destino;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDestino() {
		return getColumnOriginalValue("destino");
	}

	@JSON
	@Override
	public Date getFechaSalida() {
		return _fechaSalida;
	}

	@Override
	public void setFechaSalida(Date fechaSalida) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fechaSalida = fechaSalida;
	}

	@JSON
	@Override
	public Date getFechaLlegada() {
		return _fechaLlegada;
	}

	@Override
	public void setFechaLlegada(Date fechaLlegada) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fechaLlegada = fechaLlegada;
	}

	@JSON
	@Override
	public String getEmpresa() {
		if (_empresa == null) {
			return "";
		}
		else {
			return _empresa;
		}
	}

	@Override
	public void setEmpresa(String empresa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_empresa = empresa;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEmpresa() {
		return getColumnOriginalValue("empresa");
	}

	@JSON
	@Override
	public double getPrecio() {
		return _precio;
	}

	@Override
	public void setPrecio(double precio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_precio = precio;
	}

	@JSON
	@Override
	public int getAsientosDisponibles() {
		return _asientosDisponibles;
	}

	@Override
	public void setAsientosDisponibles(int asientosDisponibles) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_asientosDisponibles = asientosDisponibles;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Viaje.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Viaje.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Viaje toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Viaje>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ViajeImpl viajeImpl = new ViajeImpl();

		viajeImpl.setUuid(getUuid());
		viajeImpl.setViajeId(getViajeId());
		viajeImpl.setGroupId(getGroupId());
		viajeImpl.setCompanyId(getCompanyId());
		viajeImpl.setUserId(getUserId());
		viajeImpl.setUserName(getUserName());
		viajeImpl.setCreateDate(getCreateDate());
		viajeImpl.setModifiedDate(getModifiedDate());
		viajeImpl.setOrigen(getOrigen());
		viajeImpl.setDestino(getDestino());
		viajeImpl.setFechaSalida(getFechaSalida());
		viajeImpl.setFechaLlegada(getFechaLlegada());
		viajeImpl.setEmpresa(getEmpresa());
		viajeImpl.setPrecio(getPrecio());
		viajeImpl.setAsientosDisponibles(getAsientosDisponibles());

		viajeImpl.resetOriginalValues();

		return viajeImpl;
	}

	@Override
	public Viaje cloneWithOriginalValues() {
		ViajeImpl viajeImpl = new ViajeImpl();

		viajeImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		viajeImpl.setViajeId(this.<Long>getColumnOriginalValue("viajeId"));
		viajeImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		viajeImpl.setCompanyId(this.<Long>getColumnOriginalValue("companyId"));
		viajeImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		viajeImpl.setUserName(this.<String>getColumnOriginalValue("userName"));
		viajeImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		viajeImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		viajeImpl.setOrigen(this.<String>getColumnOriginalValue("origen"));
		viajeImpl.setDestino(this.<String>getColumnOriginalValue("destino"));
		viajeImpl.setFechaSalida(
			this.<Date>getColumnOriginalValue("fechaSalida"));
		viajeImpl.setFechaLlegada(
			this.<Date>getColumnOriginalValue("fechaLlegada"));
		viajeImpl.setEmpresa(this.<String>getColumnOriginalValue("empresa"));
		viajeImpl.setPrecio(this.<Double>getColumnOriginalValue("precio"));
		viajeImpl.setAsientosDisponibles(
			this.<Integer>getColumnOriginalValue("asientosDisponibles"));

		return viajeImpl;
	}

	@Override
	public int compareTo(Viaje viaje) {
		int value = 0;

		value = DateUtil.compareTo(getFechaSalida(), viaje.getFechaSalida());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Viaje)) {
			return false;
		}

		Viaje viaje = (Viaje)object;

		long primaryKey = viaje.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Viaje> toCacheModel() {
		ViajeCacheModel viajeCacheModel = new ViajeCacheModel();

		viajeCacheModel.uuid = getUuid();

		String uuid = viajeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			viajeCacheModel.uuid = null;
		}

		viajeCacheModel.viajeId = getViajeId();

		viajeCacheModel.groupId = getGroupId();

		viajeCacheModel.companyId = getCompanyId();

		viajeCacheModel.userId = getUserId();

		viajeCacheModel.userName = getUserName();

		String userName = viajeCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			viajeCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			viajeCacheModel.createDate = createDate.getTime();
		}
		else {
			viajeCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			viajeCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			viajeCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		viajeCacheModel.origen = getOrigen();

		String origen = viajeCacheModel.origen;

		if ((origen != null) && (origen.length() == 0)) {
			viajeCacheModel.origen = null;
		}

		viajeCacheModel.destino = getDestino();

		String destino = viajeCacheModel.destino;

		if ((destino != null) && (destino.length() == 0)) {
			viajeCacheModel.destino = null;
		}

		Date fechaSalida = getFechaSalida();

		if (fechaSalida != null) {
			viajeCacheModel.fechaSalida = fechaSalida.getTime();
		}
		else {
			viajeCacheModel.fechaSalida = Long.MIN_VALUE;
		}

		Date fechaLlegada = getFechaLlegada();

		if (fechaLlegada != null) {
			viajeCacheModel.fechaLlegada = fechaLlegada.getTime();
		}
		else {
			viajeCacheModel.fechaLlegada = Long.MIN_VALUE;
		}

		viajeCacheModel.empresa = getEmpresa();

		String empresa = viajeCacheModel.empresa;

		if ((empresa != null) && (empresa.length() == 0)) {
			viajeCacheModel.empresa = null;
		}

		viajeCacheModel.precio = getPrecio();

		viajeCacheModel.asientosDisponibles = getAsientosDisponibles();

		return viajeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Viaje, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Viaje, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Viaje, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Viaje)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Viaje>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Viaje.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _viajeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _origen;
	private String _destino;
	private Date _fechaSalida;
	private Date _fechaLlegada;
	private String _empresa;
	private double _precio;
	private int _asientosDisponibles;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Viaje, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Viaje)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("viajeId", _viajeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("origen", _origen);
		_columnOriginalValues.put("destino", _destino);
		_columnOriginalValues.put("fechaSalida", _fechaSalida);
		_columnOriginalValues.put("fechaLlegada", _fechaLlegada);
		_columnOriginalValues.put("empresa", _empresa);
		_columnOriginalValues.put("precio", _precio);
		_columnOriginalValues.put("asientosDisponibles", _asientosDisponibles);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("viajeId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("origen", 256L);

		columnBitmasks.put("destino", 512L);

		columnBitmasks.put("fechaSalida", 1024L);

		columnBitmasks.put("fechaLlegada", 2048L);

		columnBitmasks.put("empresa", 4096L);

		columnBitmasks.put("precio", 8192L);

		columnBitmasks.put("asientosDisponibles", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Viaje _escapedModel;

}