/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ntt.travelhub.viaje.model.impl;

import com.ntt.travelhub.viaje.model.Viaje;
import com.ntt.travelhub.viaje.service.ViajeLocalServiceUtil;

/**
 * The extended model base implementation for the Viaje service. Represents a row in the &quot;Viaje_Viaje&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ViajeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ViajeImpl
 * @see Viaje
 * @generated
 */
public abstract class ViajeBaseImpl extends ViajeModelImpl implements Viaje {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a viaje model instance should use the <code>Viaje</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ViajeLocalServiceUtil.addViaje(this);
		}
		else {
			ViajeLocalServiceUtil.updateViaje(this);
		}
	}

}