/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ntt.travelhub.reserva.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.ntt.travelhub.reserva.model.Reserva;
import com.ntt.travelhub.reserva.model.ReservaModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Reserva service. Represents a row in the &quot;Reserva_Reserva&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ReservaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReservaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReservaImpl
 * @generated
 */
@JSON(strict = true)
public class ReservaModelImpl
	extends BaseModelImpl<Reserva> implements ReservaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a reserva model instance should use the <code>Reserva</code> interface instead.
	 */
	public static final String TABLE_NAME = "Reserva_Reserva";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"reservaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"origen", Types.VARCHAR}, {"destino", Types.VARCHAR},
		{"fechaSalida", Types.TIMESTAMP}, {"fechaLlegada", Types.TIMESTAMP},
		{"mail", Types.VARCHAR}, {"dni", Types.VARCHAR},
		{"idViaje", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("reservaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("origen", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("destino", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fechaSalida", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fechaLlegada", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dni", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idViaje", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Reserva_Reserva (uuid_ VARCHAR(75) null,reservaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,origen VARCHAR(75) null,destino VARCHAR(75) null,fechaSalida DATE null,fechaLlegada DATE null,mail VARCHAR(75) null,dni VARCHAR(75) null,idViaje LONG)";

	public static final String TABLE_SQL_DROP = "drop table Reserva_Reserva";

	public static final String ORDER_BY_JPQL =
		" ORDER BY reserva.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Reserva_Reserva.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DNI_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDVIAJE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ReservaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _reservaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setReservaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _reservaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Reserva.class;
	}

	@Override
	public String getModelClassName() {
		return Reserva.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Reserva, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Reserva, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Reserva, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Reserva)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Reserva, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Reserva, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Reserva)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Reserva, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Reserva, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Reserva, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Reserva, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Reserva, Object>>();

			attributeGetterFunctions.put("uuid", Reserva::getUuid);
			attributeGetterFunctions.put("reservaId", Reserva::getReservaId);
			attributeGetterFunctions.put("groupId", Reserva::getGroupId);
			attributeGetterFunctions.put("companyId", Reserva::getCompanyId);
			attributeGetterFunctions.put("userId", Reserva::getUserId);
			attributeGetterFunctions.put("userName", Reserva::getUserName);
			attributeGetterFunctions.put("createDate", Reserva::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Reserva::getModifiedDate);
			attributeGetterFunctions.put("origen", Reserva::getOrigen);
			attributeGetterFunctions.put("destino", Reserva::getDestino);
			attributeGetterFunctions.put(
				"fechaSalida", Reserva::getFechaSalida);
			attributeGetterFunctions.put(
				"fechaLlegada", Reserva::getFechaLlegada);
			attributeGetterFunctions.put("mail", Reserva::getMail);
			attributeGetterFunctions.put("dni", Reserva::getDni);
			attributeGetterFunctions.put("idViaje", Reserva::getIdViaje);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Reserva, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Reserva, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Reserva, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Reserva, String>)Reserva::setUuid);
			attributeSetterBiConsumers.put(
				"reservaId", (BiConsumer<Reserva, Long>)Reserva::setReservaId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Reserva, Long>)Reserva::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Reserva, Long>)Reserva::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Reserva, Long>)Reserva::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Reserva, String>)Reserva::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Reserva, Date>)Reserva::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Reserva, Date>)Reserva::setModifiedDate);
			attributeSetterBiConsumers.put(
				"origen", (BiConsumer<Reserva, String>)Reserva::setOrigen);
			attributeSetterBiConsumers.put(
				"destino", (BiConsumer<Reserva, String>)Reserva::setDestino);
			attributeSetterBiConsumers.put(
				"fechaSalida",
				(BiConsumer<Reserva, Date>)Reserva::setFechaSalida);
			attributeSetterBiConsumers.put(
				"fechaLlegada",
				(BiConsumer<Reserva, Date>)Reserva::setFechaLlegada);
			attributeSetterBiConsumers.put(
				"mail", (BiConsumer<Reserva, String>)Reserva::setMail);
			attributeSetterBiConsumers.put(
				"dni", (BiConsumer<Reserva, String>)Reserva::setDni);
			attributeSetterBiConsumers.put(
				"idViaje", (BiConsumer<Reserva, Long>)Reserva::setIdViaje);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getReservaId() {
		return _reservaId;
	}

	@Override
	public void setReservaId(long reservaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_reservaId = reservaId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getOrigen() {
		if (_origen == null) {
			return "";
		}
		else {
			return _origen;
		}
	}

	@Override
	public void setOrigen(String origen) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_origen = origen;
	}

	@JSON
	@Override
	public String getDestino() {
		if (_destino == null) {
			return "";
		}
		else {
			return _destino;
		}
	}

	@Override
	public void setDestino(String destino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_destino = destino;
	}

	@JSON
	@Override
	public Date getFechaSalida() {
		return _fechaSalida;
	}

	@Override
	public void setFechaSalida(Date fechaSalida) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fechaSalida = fechaSalida;
	}

	@JSON
	@Override
	public Date getFechaLlegada() {
		return _fechaLlegada;
	}

	@Override
	public void setFechaLlegada(Date fechaLlegada) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fechaLlegada = fechaLlegada;
	}

	@JSON
	@Override
	public String getMail() {
		if (_mail == null) {
			return "";
		}
		else {
			return _mail;
		}
	}

	@Override
	public void setMail(String mail) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mail = mail;
	}

	@JSON
	@Override
	public String getDni() {
		if (_dni == null) {
			return "";
		}
		else {
			return _dni;
		}
	}

	@Override
	public void setDni(String dni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dni = dni;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDni() {
		return getColumnOriginalValue("dni");
	}

	@JSON
	@Override
	public long getIdViaje() {
		return _idViaje;
	}

	@Override
	public void setIdViaje(long idViaje) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idViaje = idViaje;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdViaje() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("idViaje"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Reserva.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Reserva.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Reserva toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Reserva>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ReservaImpl reservaImpl = new ReservaImpl();

		reservaImpl.setUuid(getUuid());
		reservaImpl.setReservaId(getReservaId());
		reservaImpl.setGroupId(getGroupId());
		reservaImpl.setCompanyId(getCompanyId());
		reservaImpl.setUserId(getUserId());
		reservaImpl.setUserName(getUserName());
		reservaImpl.setCreateDate(getCreateDate());
		reservaImpl.setModifiedDate(getModifiedDate());
		reservaImpl.setOrigen(getOrigen());
		reservaImpl.setDestino(getDestino());
		reservaImpl.setFechaSalida(getFechaSalida());
		reservaImpl.setFechaLlegada(getFechaLlegada());
		reservaImpl.setMail(getMail());
		reservaImpl.setDni(getDni());
		reservaImpl.setIdViaje(getIdViaje());

		reservaImpl.resetOriginalValues();

		return reservaImpl;
	}

	@Override
	public Reserva cloneWithOriginalValues() {
		ReservaImpl reservaImpl = new ReservaImpl();

		reservaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		reservaImpl.setReservaId(
			this.<Long>getColumnOriginalValue("reservaId"));
		reservaImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		reservaImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		reservaImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		reservaImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		reservaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		reservaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		reservaImpl.setOrigen(this.<String>getColumnOriginalValue("origen"));
		reservaImpl.setDestino(this.<String>getColumnOriginalValue("destino"));
		reservaImpl.setFechaSalida(
			this.<Date>getColumnOriginalValue("fechaSalida"));
		reservaImpl.setFechaLlegada(
			this.<Date>getColumnOriginalValue("fechaLlegada"));
		reservaImpl.setMail(this.<String>getColumnOriginalValue("mail"));
		reservaImpl.setDni(this.<String>getColumnOriginalValue("dni"));
		reservaImpl.setIdViaje(this.<Long>getColumnOriginalValue("idViaje"));

		return reservaImpl;
	}

	@Override
	public int compareTo(Reserva reserva) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), reserva.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Reserva)) {
			return false;
		}

		Reserva reserva = (Reserva)object;

		long primaryKey = reserva.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Reserva> toCacheModel() {
		ReservaCacheModel reservaCacheModel = new ReservaCacheModel();

		reservaCacheModel.uuid = getUuid();

		String uuid = reservaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			reservaCacheModel.uuid = null;
		}

		reservaCacheModel.reservaId = getReservaId();

		reservaCacheModel.groupId = getGroupId();

		reservaCacheModel.companyId = getCompanyId();

		reservaCacheModel.userId = getUserId();

		reservaCacheModel.userName = getUserName();

		String userName = reservaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			reservaCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			reservaCacheModel.createDate = createDate.getTime();
		}
		else {
			reservaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			reservaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			reservaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		reservaCacheModel.origen = getOrigen();

		String origen = reservaCacheModel.origen;

		if ((origen != null) && (origen.length() == 0)) {
			reservaCacheModel.origen = null;
		}

		reservaCacheModel.destino = getDestino();

		String destino = reservaCacheModel.destino;

		if ((destino != null) && (destino.length() == 0)) {
			reservaCacheModel.destino = null;
		}

		Date fechaSalida = getFechaSalida();

		if (fechaSalida != null) {
			reservaCacheModel.fechaSalida = fechaSalida.getTime();
		}
		else {
			reservaCacheModel.fechaSalida = Long.MIN_VALUE;
		}

		Date fechaLlegada = getFechaLlegada();

		if (fechaLlegada != null) {
			reservaCacheModel.fechaLlegada = fechaLlegada.getTime();
		}
		else {
			reservaCacheModel.fechaLlegada = Long.MIN_VALUE;
		}

		reservaCacheModel.mail = getMail();

		String mail = reservaCacheModel.mail;

		if ((mail != null) && (mail.length() == 0)) {
			reservaCacheModel.mail = null;
		}

		reservaCacheModel.dni = getDni();

		String dni = reservaCacheModel.dni;

		if ((dni != null) && (dni.length() == 0)) {
			reservaCacheModel.dni = null;
		}

		reservaCacheModel.idViaje = getIdViaje();

		return reservaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Reserva, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Reserva, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Reserva, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Reserva)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Reserva>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Reserva.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _reservaId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _origen;
	private String _destino;
	private Date _fechaSalida;
	private Date _fechaLlegada;
	private String _mail;
	private String _dni;
	private long _idViaje;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Reserva, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Reserva)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("reservaId", _reservaId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("origen", _origen);
		_columnOriginalValues.put("destino", _destino);
		_columnOriginalValues.put("fechaSalida", _fechaSalida);
		_columnOriginalValues.put("fechaLlegada", _fechaLlegada);
		_columnOriginalValues.put("mail", _mail);
		_columnOriginalValues.put("dni", _dni);
		_columnOriginalValues.put("idViaje", _idViaje);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("reservaId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("origen", 256L);

		columnBitmasks.put("destino", 512L);

		columnBitmasks.put("fechaSalida", 1024L);

		columnBitmasks.put("fechaLlegada", 2048L);

		columnBitmasks.put("mail", 4096L);

		columnBitmasks.put("dni", 8192L);

		columnBitmasks.put("idViaje", 16384L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Reserva _escapedModel;

}