/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.ntt.travelhub.reserva.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Reserva service. Represents a row in the &quot;Reserva_Reserva&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.ntt.travelhub.reserva.model.impl.ReservaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.ntt.travelhub.reserva.model.impl.ReservaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Reserva
 * @generated
 */
@ProviderType
public interface ReservaModel
	extends BaseModel<Reserva>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reserva model instance should use the {@link Reserva} interface instead.
	 */

	/**
	 * Returns the primary key of this reserva.
	 *
	 * @return the primary key of this reserva
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reserva.
	 *
	 * @param primaryKey the primary key of this reserva
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this reserva.
	 *
	 * @return the uuid of this reserva
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this reserva.
	 *
	 * @param uuid the uuid of this reserva
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the reserva ID of this reserva.
	 *
	 * @return the reserva ID of this reserva
	 */
	public long getReservaId();

	/**
	 * Sets the reserva ID of this reserva.
	 *
	 * @param reservaId the reserva ID of this reserva
	 */
	public void setReservaId(long reservaId);

	/**
	 * Returns the group ID of this reserva.
	 *
	 * @return the group ID of this reserva
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this reserva.
	 *
	 * @param groupId the group ID of this reserva
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reserva.
	 *
	 * @return the company ID of this reserva
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reserva.
	 *
	 * @param companyId the company ID of this reserva
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this reserva.
	 *
	 * @return the user ID of this reserva
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this reserva.
	 *
	 * @param userId the user ID of this reserva
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this reserva.
	 *
	 * @return the user uuid of this reserva
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this reserva.
	 *
	 * @param userUuid the user uuid of this reserva
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this reserva.
	 *
	 * @return the user name of this reserva
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this reserva.
	 *
	 * @param userName the user name of this reserva
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this reserva.
	 *
	 * @return the create date of this reserva
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this reserva.
	 *
	 * @param createDate the create date of this reserva
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this reserva.
	 *
	 * @return the modified date of this reserva
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reserva.
	 *
	 * @param modifiedDate the modified date of this reserva
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the origen of this reserva.
	 *
	 * @return the origen of this reserva
	 */
	@AutoEscape
	public String getOrigen();

	/**
	 * Sets the origen of this reserva.
	 *
	 * @param origen the origen of this reserva
	 */
	public void setOrigen(String origen);

	/**
	 * Returns the destino of this reserva.
	 *
	 * @return the destino of this reserva
	 */
	@AutoEscape
	public String getDestino();

	/**
	 * Sets the destino of this reserva.
	 *
	 * @param destino the destino of this reserva
	 */
	public void setDestino(String destino);

	/**
	 * Returns the fecha salida of this reserva.
	 *
	 * @return the fecha salida of this reserva
	 */
	public Date getFechaSalida();

	/**
	 * Sets the fecha salida of this reserva.
	 *
	 * @param fechaSalida the fecha salida of this reserva
	 */
	public void setFechaSalida(Date fechaSalida);

	/**
	 * Returns the fecha llegada of this reserva.
	 *
	 * @return the fecha llegada of this reserva
	 */
	public Date getFechaLlegada();

	/**
	 * Sets the fecha llegada of this reserva.
	 *
	 * @param fechaLlegada the fecha llegada of this reserva
	 */
	public void setFechaLlegada(Date fechaLlegada);

	/**
	 * Returns the mail of this reserva.
	 *
	 * @return the mail of this reserva
	 */
	@AutoEscape
	public String getMail();

	/**
	 * Sets the mail of this reserva.
	 *
	 * @param mail the mail of this reserva
	 */
	public void setMail(String mail);

	/**
	 * Returns the dni of this reserva.
	 *
	 * @return the dni of this reserva
	 */
	@AutoEscape
	public String getDni();

	/**
	 * Sets the dni of this reserva.
	 *
	 * @param dni the dni of this reserva
	 */
	public void setDni(String dni);

	/**
	 * Returns the id viaje of this reserva.
	 *
	 * @return the id viaje of this reserva
	 */
	public long getIdViaje();

	/**
	 * Sets the id viaje of this reserva.
	 *
	 * @param idViaje the id viaje of this reserva
	 */
	public void setIdViaje(long idViaje);

	@Override
	public Reserva cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}